#+TITLE: The web in /real time/
#+AUTHOR: David Pineda Osorio @Pineiden
#+EMAIL: dpineda@uchile.cl
#+LANGUAGE: en

* Creation of Techno Machines

Here we will learn some wonderful and hard things. Maybe i couldn't obtain all the knowledge about 
all necessary  to handle real time systems but the contents that i will provide to you will be worth it.
With all of that you can start a little application and with some more research create a wonderful techno
machine that will wonder all people.

This content is created with my living work and i intend to contribute to the commonwealth. Hence i invite 
you to do the same. Learn, create and share with the humanity your work, create commonwealth.

The technologies used in this contents are avalaible on the web and i recommend to use Gnu/Linux, some distribution
of the Debian family (Debian, Mint, Ubuntu, etc). You have to go deep on different languages: bash, python, javascript, 
typescript, erlang, postgres, lisp; and design patterns: observer pattern, model-view-controller pattern, etc.

* Install and configure the technologies

** IDEs

   Here i only can give you some some advices. Exists:
  - *pycharm* : very friendly but uses a lot of resources [[https://www.jetbrains.com/pycharm/][page]]
  - *geany* : easy to use with some limitations [[https://www.geany.org/][page]]
  - *sublime text* : easy and poweful [[https://www.sublimetext.com/][page]]
  - *emacs* : hard to use at beggining but the best (for me) [[https://www.gnu.org/software/emacs/][page]]
  - *spacemacs* : a layer over emacs, with some more features.  [[http://spacemacs.org/][page]]

  You can install some of these IDEs, try and if doesn't fix your needs change to another.

** Python

** Virtual Environment

** Django

** Postgres

** RabbitMQ

** Angular

* A General Schema

* The Backend

* The Channel

* The Frontend

* The Messages

* Create an App on the Backend

* Create an App on the Frontend

* The Websocket Service

* Binding the Websocket to your App

* The End
